### ISSUE TITLE
イメージのビルドに失敗する頻度が高い

### ISSUE THREAD

**Issue by 3socha** [theoremoon/ShellgeiBot-Image#108]
## 現象

- 最近 Go と Chromium のダウンロードが失敗してビルドできないことが多い
    - [CircleCI](https://circleci.com/gh/theoremoon/ShellgeiBot-Image/tree/master)

<img width="1643" alt="JobStatus" src="https://user-images.githubusercontent.com/5246144/85941059-640da600-b95b-11ea-9d7d-9cc94aa64cd0.png">

### Go

```
#30 [go-builder 2/5] RUN curl -sfSL --retry 5 https://dl.google.com/go/go1.1...
#30 3.772 curl: (56) OpenSSL SSL_read: Connection reset by peer, errno 104
#30 ERROR: executor failed running [/bin/sh -c curl -sfSL --retry 5 https://dl.google.com/go/go1.14.1.linux-amd64.tar.gz -o go.tar.gz     && tar xzf go.tar.gz -C /usr/local     && rm go.tar.gz]: runc did not terminate sucessfully
```

### Chromium

```
#95 [general-builder 22/22] RUN REVISION=$(curl -sS --retry 3 "https://www.g...
#95 2.900 curl: (56) OpenSSL SSL_read: Connection reset by peer, errno 104
#95 ERROR: executor failed running [/bin/sh -c REVISION=$(curl -sS --retry 3 "https://www.googleapis.com/download/storage/v1/b/chromium-browser-snapshots/o/Linux_x64%2FLAST_CHANGE?alt=media")     && curl -sfSL --retry 3 -o chrome-linux.zip "https://www.googleapis.com/download/storage/v1/b/chromium-browser-snapshots/o/Linux_x64%2F${REVISION}%2Fchrome-linux.zip?alt=media"]: runc did not terminate sucessfully
```

## 対策案

- #106 : curl の再試行回数を増やしてみる
  - `curl` の `--retry` は、転送時の一時的なエラー（タイムアウト, HTTP 408, HTTP 5xx）の場合の再試行回数を指定するためのもので、このエラーはクライアント側の問題っぽいので効いてなさそう
- Circle CI でビルドする時間帯を変更
  - https://github.com/horo17/measure-circleci-performance で 15分毎に Go と Chromium のダウンロードを試してみて、空いてそうな時間帯を探ってみる
  - 見られるか分からないけど：[CircleCI Insights](https://circleci.com/build-insights/gh/horo17/measure-circleci-performance/master)

**Comment by theoremoon** [comment]
issueありがたいです :pray: Insightsみれないので結果お待ちしてますね

**Comment by 3socha** [comment]
- 6/28 17:05 - 6/29 13:20
    - ![200628](https://user-images.githubusercontent.com/5246144/85973653-6c72e900-ba0e-11ea-9e2a-37706bf6a539.png)
        - 赤矢印は1時間毎の目印
    - CircleCI でジョブがキューに入ってる時間（グレー）と Spin up（緑の大半）時間がほとんど
    - グラフからはわかないが、Go / Chromium のダウンロードはいずれも 1~2 秒程度で済んでいる
        - （もうちょっと上手いモニタリング方法ないかな...）
- ダウンロードの失敗は、今のところ観測していないため、もう少し継続して見てみる

**Comment by theoremoon** [comment]
なんとなく良さそうなのでcloseします。juliaとかでまた壊れたら #109 と同様の対処をする方向で
