### ISSUE TITLE
failed to test rustc

### ISSUE THREAD

**Issue by theoremoon** [theoremoon/ShellgeiBot-Image#112]
rustcってそもそも動くんでしたっけ

https://app.circleci.com/pipelines/github/theoremoon/ShellgeiBot-Image/340/workflows/8c3dbe56-f4ec-4c47-ae39-cc319707684b/jobs/675/steps

**Comment by theoremoon** [comment]
普通にrustcでコンパイルしようとしてもtoolchainに関するエラーで怒られていたはずだし、rustcのテストをする意味、なさそう。入れてるのは何でだったかな

**Comment by 3socha** [comment]
toolchain を自分で取得したら一応使えるようにという配慮だったかなぁ。
シェル芸bot では使えないので不要っちゃ不要だが。

**Comment by theoremoon** [comment]
rargsとforestをcargoでインストールしてるのでそれ自体は必要っぽいですね。動かないことを明示するためにエラーが出ることをtestするのが良さそうだと思ってます

**Comment by theoremoon** [comment]
あ、今もそうなってるのか。

**Comment by 3socha** [comment]
toolchain がない状態での `rustc --help` のメッセージが変更されたようですね。

```diff
# rustc --help
- error: no default toolchain configured
+ error: no override and no default toolchain set
```
