### ISSUE TITLE
Node.jsのバージョンが古めかしく感じました

### ISSUE THREAD

**Issue by butackle** [theoremoon/ShellgeiBot-Image#128]
現在(2020/12/14)、シェル芸ボットのNode.jsのバージョンはv12.18.2なのですが、Node.jsの安定版の最新バージョンはv14.15.1なので、ややバージョンが古めかしいです。

Node.jsのリリーススケジュールは、こちらから確認できます。
https://nodejs.org/en/about/releases/

おそらく、ココの部分でNode.jsを入れているのだと思いますが、この方法だとどのNode.jsのバージョンが入れられているのか分からないので混乱の元かなと思いました。(混乱しているのは自分だけかもしれないですが)
https://github.com/theoremoon/ShellgeiBot-Image/blob/master/Dockerfile#L83

Node.jsは、バージョンが頻繁に更新されたり、普段使っているバージョンではないバージョンでの検証などをしたりするのが割と多いので、通常はバージョンマネージャ(nodebrew・nodenv)などを用いてインストールすることが多いです。
が、シェル芸ボットで、あまりNode.jsのバージョンを切り替えて遊ぶようなニーズが無さそうな気もするので、個人的にはhttps://nodejs.org/dist/あたりからbinary archiveを取得して下記のような形で展開しても良いかもしれないです。
https://github.com/nodejs/help/wiki/Installation#how-to-install-nodejs-via-binary-archive-on-linux

自分がプルリクを出したいとは思っているのですが、もしかしたら日々の雑務に忙殺されて忘れるかもしれないと思ったので、念のため先にこちらで書き記しておきます。

**Comment by 3socha** [comment]
（勝手な）メンテナンス方針として：
Node.js に限らないですが、最新のバージョンを使いたいとか、特定のバージョンに固定したいという要求がない限りは、メンテナンス/ビルド/配布が楽になるよう、Ubuntu のパッケージマネージャで入るものを入れてました
nodejs はこのあたり：
https://github.com/theoremoon/ShellgeiBot-Image/blob/1b6d0bc6ffc099422d616ca6727b94b7558cab13/Dockerfile#L307

何らかのウェブアプリケーションを動作させるなら、LTS の最新版で動作させるのが良いかもしれませんが、シェル芸botはそういう用途ではないのかなと捉えています。
個々のソフトウェアのアップデートを追いかけるのは結構大変なので、半年に一度の Ubuntu バージョンアップに追従していれば、メンテナンスコストを抑えつつ、概ね新しいものにもついていけるかなという考えです。

ただ、利用者がいてナンボな気もするので、特定の処理系で最新版とか特定のバージョンが使えたら嬉しい、というようなリクエストには、ある程度応えても良いのかなと思います。

@theoremoon 見解ください

**Comment by theoremoon** [comment]
- 管理はできるだけ楽な方が良い（のでパッケージマネージャの提供する node を使っています）
- 使いたい人がいるならそちらを優先したい

ので安定版がほしいというニーズがあればそちらに対応していきたいです。ただそれでバージョン番号を固定してインストールをしてしまうと #127 みたいな issue の処理で大変になるので、導入方法をどうするかは考えましょう。 常にstableなバイナリが得られるリンクを使うとかですね

**Comment by 3socha** [comment]
#129 の対応で、自動的に最新の LTS 版が利用できているようなので良さそう。

- [Node.js リリース一覧](https://nodejs.org/ja/download/releases/)
- [12/17](https://twitter.com/minyoruminyon/status/1339448400543055872) v14.15.2
- [12/19](https://twitter.com/minyoruminyon/status/1340207968927662080) v14.15.3

**Comment by butackle** [comment]
@3socha @theoremoon 
解決したと思っているので閉じますー、お忙しいなか対応していただき、ありがとうございました。
お役に立てず、申し訳ありません(>人<)
