### ISSUE TITLE
Go のビルドがこける

### ISSUE THREAD

**Issue by 3socha** [theoremoon/ShellgeiBot-Image#135]
- [CircleCI (955)](https://app.circleci.com/pipelines/github/theoremoon/ShellgeiBot-Image/613/workflows/062a8411-7569-4455-aa27-0e76b09e862f/jobs/955)
- https://github.com/mattn/longcat/pull/42 で Go 1.16 が要求されるようになったため

---

- Go 1.16 だと golang/dep が利用できず、dep に依存している YuheiNakasaka/sayhuuzoku がビルドできない
    - sayhuuzoku を外してしまう?
    - 複数バージョンの go-builder を用意して別々にビルドする?

**Comment by theoremoon** [comment]
> Go 1.16 だと golang/dep が利用できず……

ってどこ情報でしょう？ 実は ShellgeiBot-Imageの goのversionを1.16に上げるだけでも良さそうと思っています

**Comment by theoremoon** [comment]
sayhuuzokuにModules移行のPRを出してみたので、これが取り込まれればbuilderを分ける必要はないかもしれません

https://github.com/YuheiNakasaka/sayhuuzoku/pull/5

**Comment by 3socha** [comment]
手元 の Go1.16 で dep が使えないか試してたんですが、こんな具合でした。

```
% go version
go version go1.16 darwin/amd64
% go install github.com/golang/dep/cmd/dep@latest
(snip)
# github.com/golang/dep/gps
.gvm/pkgsets/go1.16/global/pkg/mod/github.com/golang/dep@v0.5.4/gps/constraint.go:103:21: cannot use sv (type *semver.Version) as type semver.Version in field value
.gvm/pkgsets/go1.16/global/pkg/mod/github.com/golang/dep@v0.5.4/gps/constraint.go:122:16: invalid type assertion: c.(semver.Version) (non-interface type *semver.Constraints on left)
.gvm/pkgsets/go1.16/global/pkg/mod/github.com/golang/dep@v0.5.4/gps/constraint.go:149:4: undefined: semver.Constraint
```

PR 早い...!

**Comment by theoremoon** [comment]
なるほど。 `go get` 自体は動いたのでそちらでの依存解析はできていそうだけど、depを落としてきて自前でやろうとするとだめなんですね
