### ISSUE TITLE
base85コマンドの追加

### ISSUE THREAD

**Issue by redpeacock78** [theoremoon/ShellgeiBot-Image#164]
[Ascii85](https://ja.wikipedia.org/wiki/Ascii85)(Adobe実装)に則ってエンコード及びデコードを行うツールを作成致しましたので追加のほど宜しくお願い致します。

base85: https://github.com/redpeacock78/base85

```bash
$ base85 <<<"date"
<~A79Rk$3~>

$ base85 -d <<<'<~A79Rk$3~>' | sh
金 11 12 00:38:16 JST 2021

$ sushiro -l | base85 | base85 -d
たら白子
```

**Comment by 3socha** [comment]
調べてみると、[ruby-ascii85](https://rubygems.org/gems/Ascii85/versions/1.0.3) ってのが apt に用意されているようでした。

```sh
$ ascii85 -h
Usage: ascii85 [OPTIONS] [FILE]
Encodes or decodes FILE or STDIN using Ascii85 and writes to STDOUT.
    -w, --wrap COLUMN                Wrap lines at COLUMN. Default is 80, use 0 for no wrapping
    -d, --decode                     Decode the input
    -h, --help                       Display this help and exit
        --version                    Output version information
```

@redpeacock78 ruby-ascii85 と比べて、作成された base85 コマンドの方が優れている点ってありますでしょうか。

**Comment by redpeacock78** [comment]
@3socha  [ruby-ascii85](https://rubygems.org/gems/Ascii85/versions/1.0.3)の存在を知らなかったので現時点でのそれぞれの仕様と動作の共通点・差異点を検証してみました。

- 試験環境
  - マシン
    - MacBook Pro (Retina, 15-inch, Mid 2015)
    - 2.2 GHz Quad Core Intel Core i7
    - 16 GB 1600 MHz DDR3
    - macOS Big Sur 11.6.1
  - Docker
    ```bash
    $ docker --version 
    Docker version 20.10.7, build f0df350
    ```
  - Docker Container (Ubuntu)
    ```bash
    $ uname -a
    Linux 309627a79952 5.10.25-linuxkit #1 SMP Tue Mar 23 09:27:39 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

    $ cat /etc/os-release
    NAME="Ubuntu"
    VERSION="20.04.3 LTS (Focal Fossa)"
    ID=ubuntu
    ID_LIKE=debian
    PRETTY_NAME="Ubuntu 20.04.3 LTS"
    VERSION_ID="20.04"
    HOME_URL="https://www.ubuntu.com/"
    SUPPORT_URL="https://help.ubuntu.com/"
    BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
    PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
    VERSION_CODENAME=focal
    UBUNTU_CODENAME=focal

    $ bash --version
    GNU bash, version 5.0.17(1)-release (x86_64-pc-linux-gnu)
    Copyright (C) 2019 Free Software Foundation, Inc.
    License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

    This is free software; you are free to change and redistribute it.
    There is NO WARRANTY, to the extent permitted by law.
    ```
  - インストール方法
    - `ruby-ascii85`は`apt update && apt install -y ruby-ascii85`にてインストール。
    - `base85`は`curl`にて[Releaseページ](https://github.com/redpeacock78/base85/releases)から`base85-linux-x86`を取得し`chmod`で実行権限を付与。

- 共通点
  - Ascii85(Adobeで実装されているエンコードしたバイトシーケンスを`<~` と`~>`で囲む方式 )を採用している。
  - ファイル及び標準入力から入力されたテキスト及びバイナリデータに対応している。
  - テキスト及びバイナリデータを標準出力する。
- 差異点
  - コマンド名の違い
    - `base85`の方は`base64`や`base32`に名前を合わせた。
    - `ruby-ascii85`はコマンド名が`ascii85`なので`base85`より1文字だけ長い。
  - `-w, --wrap`オプションの有無
    - `ruby-ascii85`でのエンコード結果は**80文字**で改行されるため実装されていると考えられる。
    - `base85`でのエンコード結果は改行せず**1行**で出力するため実装していない。
  - エンコード結果の表示の違い
     - `ruby-ascii85`
       ```bash
       $ echo OK|ascii85
       <~:J2#~>$ # <- 改行されない
       ```
    - `base85`
      ```bash
      $ echo OK|base85 
      <~:J2#~> # <- 改行される
      $
      ```
       ※ ちなみにGNU coreutils版の`base64`では改行されました。
  - 実行速度
    ざっくりforで1万回測定。
    - エンコード
      - `ruby-ascii85`
        ```bash
        $ time { for i in {1..10000}; do ascii85 <<<"Ascii85は、7ビットの印字可能なASCII文字を使用した符号化方式です。Base85とも呼ばれます。" ; done } >/dev/null

        real	13m26.699s
        user	10m41.130s
        sys	2m44.665s
        ```
      - `base85`
        ```bash
        $ time { for i in {1..10000}; do base85 <<<"Ascii85は、7ビットの印字可能なASCII文字を使用した符号化方式です。Base85とも呼ばれます。" ; done } >/dev/null

        real	6m32.686s
        user	4m26.108s
        sys	2m10.185s
        ```
    - デコード
      ```bash
      $ base85 <<<"Ascii85は、7ビットの印字可能なASCII文字を使用した符号化方式です。Base85とも呼ばれます。" >> test.txt
      $ cat test.txt
      <~6$$OMBfItT1Ggmm1,(Ff1,V!q1Ggmm1,(Ce1,(FA>Ve2m>V[uh>V\&j>Ve2m>V[uh>V[uh>Ve2m>V[uh>V\#f>Ve2m>V[uf>V\/p>Ve2o>V\#k>V\2k>Ve2o>V\/o>V\&n>Ve2o>V\#m>V\/q>Ve5k>V[uh>V\5q>Ve2m>V[uf>V\/l5uU-B8R+&.2I&!m2I&!k2dA-q2-_mo2-_ml2dA-q1L)[h10cRi10cUl1gDdp2-_mq2dA-q2dA*n1gDdn0O-Cj1L)[h0jHIh2dA-q1L)[h0jHIi2dA-q2dA*q1gDdm2I&$p2-_mk2dA*r2dA-q2-_mk1gDdk2I&$p2I&!m2I&!r0jHLk2-_mq1gDdj2dA-q1L)[h0jHIj2dA-q1L)[h0jHIi0jHLk1L)[h0O-@e1.#DjAN2PP1Ggmm1,(Ff1,Uaj1Ggmm1,(Ig1,(Ig1Ggso1,:Rh1,h$p1Ggmm1,(Ff1,^gk1Ggmm1,(Ig1,1Uj1Ggmm1,(Ff1,h*r1Ggmm1,(Ff1,CXi1Ggmm1,(Ce1,(Hjzz~>
      ```
      - `ruby-ascii85`
        ```bash
        $ time { for i in {1..10000}; do ascii85 test.txt ; done } >/dev/null

        real	12m24.408s
        user	10m10.762s
        sys	2m13.586s
        ```
      - `base85`
        ```bash
        $ time { for i in {1..10000}; do base85 test.txt ; done } >/dev/null

        real	5m56.317s
        user	4m19.403s
        sys	1m40.676s
        ```
     以上の結果からざっくりとではあるものの、エンコード及びデコード処理に於いて`base85`は`ruby-ascii85`と比較して**約2倍以上**高速に処理が可能。
  - 配布形式の違い
    - `ruby-ascii85`
      ```bash
      $ file $(type ascii85|awk '$0=$3')
      /usr/bin/ascii85: Ruby script, UTF-8 Unicode text executable
      ```
    - `base85`
      ```bash
      $ file $(type base85|awk '$0=$3')
      /usr/local/bin/base85: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 3.2.0, BuildID[xxHash]=0cd1fde8efdb9b98, with debug_info, not stripped
      ```
      `ruby-ascii85`はRuby Scriptなので`ruby-ascii85`以外に依存関係をインストールする必要があるが、`base85`はバイナリでの配布も行なっているので実行ファイル一つで完結する。

以上のことから、

- インストールが簡単。
- `base64`に名前を近づけているので文字数が少なく覚えやすい。(Twitter的には重要な気がする)
- エンコードでは結果が常に1行で改行位置が常に最終文字列端なので扱いやすい気がする。
- オプションが少なくシンプル。
- 処理速度が`ruby-ascii85`よりも高速。

というところが`ruby-ascii85`と比較して`base85`が優れているところでは無いかなと思います。

**Comment by 3socha** [comment]
@redpeacock78 調査ありがとうございます。速いのは良いことですね！
#165 で base85 を追加する Pull Req 書いてみました。

---

動作確認していて1点気になったのですが、4byte の倍数の文字列を base85 encode した時に、他の実装（Ruby, Python）とは出力が異なり、padding? の `zz` が入っているようでした。zz があっても decode に問題はなさそう?

```sh
$ echo -n hoge | base85
<~BQ%Npzz~>
```

```sh
$ echo -n hoge | ascii85
<~BQ%Np~>
```

**Comment by redpeacock78** [comment]
@3socha 上記の環境でも試してみました。
```bash
# Encode ascii85 -> Decode base85
$ base85 -d <<<$(echo -n hoge | ascii85)
hoge # <- 改行なし

# Encode base85 -> Decode ascii85
$ ascii85 -d <<<$(echo -n hoge | base85)
hoge # <- 改行なし
```
問題ありませんでした。

ただ気にはなったので他の実装に合わせて修正したので`base85`のバージョンがv.0.0.11になりましたので宜しく御願い致します🙏
