### ISSUE TITLE
master以外のブランチからのマージリクエストでCircleCIのテストが実行されない

### ISSUE THREAD

**Issue by jiro4989** [theoremoon/ShellgeiBot-Image#70]
設定みてみます
https://github.com/theoremoon/ShellgeiBot-Image/pull/69#issuecomment-542737345

**Comment by jiro4989** [comment]
@theoremoon 
こちらの「Build forked pull requests」という設定って、ONにするの試されましたか？

![2019-10-17-002504_1894x825_scrot](https://user-images.githubusercontent.com/13825004/66934162-0b200b00-f075-11e9-963f-773a1ead059d.png)

**Comment by theoremoon** [comment]
現状こんな感じです 
![image](https://user-images.githubusercontent.com/7302203/66979035-13189300-f0e7-11e9-8393-9618248966ce.png)

**Comment by jiro4989** [comment]
ありがとうございます。見てみます。

CircleCIだけにこだわらないのでしたら、TravisCIとかにもリポジトリを登録してしまって、PRのテストはそっちで見る、というアプローチもやり方としてはあるかな、と思いました。
管理コストが増えるので最終手段かと思いますが。

**Comment by 3socha** [comment]
CircleCI では、フォーク先のリポジトリで（フォーク先の CircleCI で）トリガーされた場合、同じコミットで Pull Request がフォーク元に来てもトリガーされないようですね。
ドキュメントやフォーラムでは見つけられませんでしたが、過去に自分のリポジトリで試していたところでは、そんな挙動をしていました。

**Comment by theoremoon** [comment]
うーんなるほど、それじゃ仕方ないですね……

**Comment by theoremoon** [comment]
逆にBuild forked pull requestsをOffにするとうまく行くような気がしたのでそうしてみました。次のPull Requestが飛んできたときにどうなったか見てみます

**Comment by jiro4989** [comment]
試しに今PR送ってみましょうか？

**Comment by jiro4989** [comment]
https://github.com/theoremoon/ShellgeiBot-Image/pull/72
うーん、ダメっぽいですね

**Comment by jiro4989** [comment]
#73 masterからmasterへのPRでも動かず。うーん...

**Comment by jiro4989** [comment]
#66 のとかでは普通にテスト動いていたみたいですけれど、どのタイミングからテスト走らなくなったんでしょう？

**Comment by jiro4989** [comment]
テストが動いていたタイミングとmasterのdiff出してみましたが、config.yml的には問題なさそうなんですよね

```bash
$ g diff 3ff4e2d master | cat | head -n 20
diff --git a/.circleci/config.yml b/.circleci/config.yml
index 2c96c7a..3c8d21b 100644
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -18,8 +18,9 @@ jobs:
       - run:
           name: Build Docker image
           command: |
-            apk add --no-progress git
+            apk add --no-progress git jq curl
             git log --pretty="format:%h %cd %s [%an]" --date=iso -n 20 > revision.log
+            ./.circleci/get_build_log.sh > ci_build.log
             docker build -t ${DOCKER_IMAGE} --progress=plain .
       - run:
           name: Test Docker image
diff --git a/.circleci/get_build_log.sh b/.circleci/get_build_log.sh
new file mode 100755
index 0000000..fbcee23
--- /dev/null
+++ b/.circleci/get_build_log.sh
```

**Comment by theoremoon** [comment]
うーん、時間かかるかもしれないけどサポートに問い合わせてみます

**Comment by theoremoon** [comment]
いやこれか…… https://support.circleci.com/hc/en-us/articles/360008097173-Why-aren-t-pull-requests-triggering-jobs-on-my-organization-

**Comment by theoremoon** [comment]
英語読めないけどforkした側がどうにかしないとだめで、forkされる側は対処できない？

**Comment by jiro4989** [comment]
> これは通常、ユーザーがCircleCIのプロジェクト自体ではなく、個人アカウントでプロジェクトフォークをフォローしているときに発生します。これにより、ユーザーの個人アカウントでジョブがトリガーされます。

僕はCircleCIの個人アカウントを持っていますし、forkした側がどうにかしないとダメっぽい気がしますね

**Comment by jiro4989** [comment]
> 逆にBuild forked pull requestsをOffにするとうまく行くような気がしたのでそうしてみました。次のPull Requestが飛んできたときにどうなったか見てみます

Build forked pull requests をONにしていただいて、
僕のほうではリポジトリフォークしなおしてCircleCIアカウントのプロジェクトの設定見直してから
PRを送って確認してみたいです

**Comment by theoremoon** [comment]
@jiro4989 了解です。 Build forked pull requests を ONにしました

**Comment by theoremoon** [comment]
それにしてもこれはforkされる側から制御できても良さそうなのにだめなのかぁ。

**Comment by jiro4989** [comment]
#75 masterからPRしてみたら動きました

**Comment by jiro4989** [comment]
#76 masterとは別の名前のブランチを切ってPRしてみても動きましたー

**Comment by theoremoon** [comment]
:tada: そちら側で設定を変えたら良い感じになったということですか？

**Comment by jiro4989** [comment]
はい、アカウントからそもそもプロジェクトを除外した感じです。

**Comment by jiro4989** [comment]
僕のCircleCIアカウント側のほうにforkしたプロジェクトを登録したのがまずかったのかなぁと。

DockerfileとかのビルドがCIでパスするか検証しようとして
CircleCIアカウントに追加したのがまずかった、と考えてます。

**Comment by jiro4989** [comment]
先程の問い合わせの件もありますし
forkしたプロジェクトを個人アカウントに登録すると、
fork元のプロジェクトでトリガーされなくなるみたいですね

**Comment by theoremoon** [comment]
うーんなるほど、了解です。

とすると
Pull Reqに対してCIが走るかどうかはmasterブランチかは関係なくて

Pull Reqが走った→ええやん
走らない→Fork先の人が自分でCI回しているのでそちらを見に行く

とすればよいわけですね。調査までしていただいてありがとうございます。CIが走っていることがわかれば十分なので運用だけ変えて解決っぽいですね。

**Comment by theoremoon** [comment]
というわけでcloseします
