### ISSUE TITLE
Ubutnu 19.10 以降

### ISSUE THREAD

**Issue by theoremoon** [theoremoon/ShellgeiBot-Image#77]
とりあえず建てとけ。目下 snapdが動かなくて chromeのインストールが難しいらしい

**Comment by 3socha** [comment]
[こ](https://forum.snapcraft.io/t/snapd-in-docker/177) [の](https://github.com/ogra1/snapd-docker) あたりを参考に試してる

**Comment by 3socha** [comment]
以下、Ubuntu 19.10 移行のハードルです。

## Chromium

- ubuntu 19.10 から、chromium は snap パッケージに移行した
  - deb パッケージの chromium-browser は snap 版へ誘導するのみ
  - [dev](https://launchpad.net/~chromium-team/+archive/ubuntu/dev) / [beta](https://launchpad.net/~chromium-team/+archive/ubuntu/beta) にもやはり 19.10 版がない
- `snap` コマンドで snap パッケージをインストールするには `snapd` が動いている必要があるが、docker build 時には特権が使えないため、`systemd`, `snapd` 等を起動することができない（または難しい）
  - snap パッケージのアプリケーションを動かす場合も、snapd が動いている必要がある?
  - Docker ベースのシェル芸bot ととても相性が悪い

### snapd 以外で chromium をインストールする方法検討

- un-official なビルドを利用 ... あまりやりたくない
- 自前でビルド ... ビルドに多くのリソースが必要でちょーたいへん
- 他のマシンで snap パッケージをダウンロードして unsquashfs して配置 ... これもとても面倒っぽい

### 結局

- すみません、降参です
- chromium-browser を外しても良いなら外してしまいたい

## .NET Core

- [パッケージリポジトリ](https://packages.microsoft.com/ubuntu/19.10/prod/) は用意されているけど、まだ何も登録されていない
- そのうち dotnet-sdk-3.0 が登録されるんじゃないかな...と期待

**Comment by 3socha** [comment]
いやまてよ。
[Download Chromium](https://www.chromium.org/getting-involved/download-chromium) にリンクがある [chromium-latest-linux](https://github.com/scheib/chromium-latest-linux) スクリプトでいけるんじゃないか。
