### ISSUE TITLE
Common Lisp処理系のインストール

### ISSUE THREAD

**Issue by eggplants** [theoremoon/ShellgeiBot-Image#87]
要望です. `Common Lisp`をシェル芸で使ってみたいです.
処理系は[roswell], [sbcl], [clisp]なんでもいいと思います.
ご検討のほどよろしくお願いします…！

[roswell]: https://github.com/roswell/roswell
[sbcl]:http://www.sbcl.org/
[clisp]: https://lispuser.net/commonlisp/clisp.html

**Comment by theoremoon** [comment]
とりあえず手軽に入れられた clisp でやってみています #88  。roswell + t-sin/one をやりたかったのはあるんですが、roswellが入ってくると気を配るべき範囲が広くなりすぎそうだったので一旦は clisp だけに留めて、今後の需要を見て判断、ということにしようと思います

**Comment by eggplants** [comment]
!!!ご対応ありがとうございます!!!
